### ISSUE TITLE
delete user does not work

### ISSUE THREAD

**Issue by zamrokk** [casbin/jcasbin#16]
if I delete a user it does not delete it but it removes him from all groups
if i can enforce , permissions remain so i can still get a positive access answer using this user

**Comment by zamrokk** [comment]
this fix, removes also old permissions to a future deleted user

`/**
     * deleteUser deletes a user.
     * Returns false if the user does not exist (aka not affected).
     *
     * @param user the user.
     * @return succeeds or not.
     */
    public boolean deleteUser(String user) {
    	removeFilteredPolicy(0, user);
        return removeFilteredGroupingPolicy(0, user);
    }`

**Comment by hsluoyz** [comment]
@zamrokk , yes, it's a bit weird that deleting a user doesn't delete his permissions. ``deleteUser()`` only deletes the roles for the user. You should also use ``deletePermissionsForUser()`` to delete the user's all permissions.

But currently, it's hard to change the API, because Casbin in all languages (Go, Java, Node.js, Python, PHP..) follows this semantics. We will try to improve our API reference docs to make the meaning of the API clearer. Thanks.

**Comment by zamrokk** [comment]
deletePermissionsForUser   is    removeFilteredPolicy(0, user);    in the java implementation

Thank you for the answer. We now used this version for our side
